AWSTemplateFormatVersion: 2010-09-09
Description: RaiseTech-Security_layer

Parameters:
  AllowedIPAddress:
    Type: String
    Description: The allowed IP address to access the instance (e.g.)221.246.36.241/32
    Default: 0.0.0.0/0 # IPアドレスが変更になった際はセキュリティグループの設定値を変更する必要性が有る

Resources:
  SecurityGroupEC2RaiseTech:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SecurityGroupEC2RaiseTech
      GroupName: SecurityGroupEC2RaiseTech
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref AllowedIPAddress
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: SecurityGroupEC2RaiseTech
      VpcId: !ImportValue NetworkLayer-RaiseTechVPC

  SecurityGroupRDSRaiseTech:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SecurityGroupRDSRaiseTech
      GroupName: SecurityGroupRDSRaiseTech
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref SecurityGroupEC2RaiseTech
      Tags:
        - Key: Name
          Value: SecurityGroupRDSRaiseTech
      VpcId: !ImportValue NetworkLayer-RaiseTechVPC

  SecurityGroupALBRaiseTech:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SecurityGroupALBRaiseTech
      GroupName: SecurityGroupALBRaiseTech
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: SecurityGroupALBRaiseTech
      VpcId: !ImportValue NetworkLayer-RaiseTechVPC

Outputs:
  SecurityGroupEC2RaiseTech:
    Value: !Ref SecurityGroupEC2RaiseTech
    Export:
      Name: SecurityLayer-SecurityGroupEC2RaiseTech

  SecurityGroupRDSRaiseTech:
    Value: !Ref SecurityGroupRDSRaiseTech
    Export:
      Name: SecurityLayer-SecurityGroupRDSRaiseTech

  SecurityGroupALBRaiseTech:
    Value: !Ref SecurityGroupALBRaiseTech
    Export:
      Name: SecurityLayer-SecurityGroupALBRaiseTech
